development:
  adapter: postgresql
  encoding: unicode
  database: alan_development
  pool: 5
  username: postgres
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: alan_test
  pool: 5
  username: postgres
  host: localhost
  password:
